export interface TaxonomyStore {
  denominations: string[];
  worshipStyles: string[];
  ministries: string[];
  facilities: string[];
  languages: string[];
  ministryExperience?: string[];
  skills?: string[];
  rolesInterested?: string[];
  training?: string[];
}

export const INITIAL_TAXONOMIES: TaxonomyStore = {
  denominations: [
    "Adventist",
    "Anabaptist",
    "Anglican / Episcopal",
    "Apostolic Church",
    "Assemblies of God",
    "Baptist",
    "Eastern Catholic",
    "Independent",
    "Jehovah's Witnesses",
    "LDS / Latter-day Saints",
    "Lutheran",
    "Messianic Jewish",
    "Methodist",
    "Non-Denominational",
    "Old Catholic",
    "Oriental Orthodox",
    "Orthodox",
    "Pentecostal",
    "Presbyterian",
    "Reformed",
    "Restorationist",
    "Roman Catholic",
    "Salvation Army"
  ],
  worshipStyles: [
    "Blended Worship",
    "Charismatic / Spirit-Filled Worship",
    "Contemporary Worship",
    "Gospel Worship",
    "Multicultural Worship",
    "Online / Digital Worship",
    "Reflective / Soaking Worship",
    "Traditional Worship"
  ],
  ministries: [
    "Addiction Recovery Ministry",
    "Adult Education",
    "Bereavement / Funeral Support",
    "Bible College / Training Center",
    "Bible Study / Small Groups",
    "Children’s Ministry",
    "Childrens",
    "Christian Book Store",
    "Clothing Ministry",
    "Community Service",
    "Counseling",
    "Counselling Services",
    "Crisis Response / Disaster Relief",
    "Day Care",
    "Discipleship Ministry",
    "Environmental / Creation Care Ministry",
    "Evangelism / Street Outreach",
    "Family",
    "Family Life Ministry",
    "Finance / Stewardship Ministry",
    "Financial Assistance / Benevolence Ministry",
    "Food Pantry",
    "Food Pantry / Feeding Program",
    "Funerals",
    "Homeless Outreach",
    "Hospital / Visitation Ministry",
    "Leadership Development",
    "Local Community Service",
    "Marketplace / Professionals Ministry",
    "Marriage Enrichment / Couples Ministry",
    "Media / Tech Team",
    "Men’s Ministry",
    "Mental Health Support",
    "Mentorship Program",
    "Military / Veterans Ministry",
    "Missions",
    "Missions / Global Outreach",
    "Music Ministry",
    "New Believers Class",
    "Nursery",
    "Online Church / Digital Ministry",
    "Orphanage",
    "Outreach Ministry",
    "Parenting Support",
    "Prayer & Healing Ministry",
    "Prayer Ministry",
    "Pre-School",
    "Prison / Jail Ministry",
    "Prison Ministry",
    "Radio Ministry",
    "Refugee & Immigrant Support",
    "School",
    "Security Team",
    "Seniors / Golden Age Ministry",
    "Sports / Recreation Ministry",
    "Student / Campus Ministry",
    "Sunday School / Christian Education",
    "Television Ministry",
    "Theology / Apologetics Ministry",
    "Transportation Ministry",
    "Volunteer Coordination",
    "Women’s Ministry",
    "Worship Ministry",
    "Youth Ministry"
  ],
  facilities: [
    "Accessibility Ramps / Elevators",
    "Auditorium",
    "Baptistry / Baptism Pool",
    "Bible Study Rooms",
    "Bookstore / Gift Shop",
    "Chapel",
    "Children’s Playground",
    "Church Café / Coffee Shop",
    "Church Office Building",
    "Computer Lab / Media Room",
    "Conference Room / Boardroom",
    "Counseling Center",
    "Disaster Relief Center",
    "Fellowship Hall",
    "Food Pantry",
    "Free Wifi",
    "Funeral / Memorial Service Facilities",
    "Guest Housing / Missionary Housing",
    "Handicapped Parking",
    "Health Care",
    "Hearing Assistance System",
    "Kitchen / Dining Hall",
    "Library / Resource Center",
    "Live Stream / Online Service Support",
    "Live Streaming Equipment",
    "Lounge / Welcome Center",
    "Mission Support Office",
    "Multipurpose Hall",
    "Nursery / Crèche",
    "Outdoor Picnic Area",
    "Parking Available",
    "Parsonage / Pastor’s Residence",
    "Prayer Room",
    "Projectors / Screens",
    "Recording Studio",
    "Restrooms",
    "Security",
    "Sound Booth / Audio-Visual Room",
    "Stage / Lighting System",
    "Sunday School Classrooms",
    "Training / Discipleship Center",
    "Translation / Interpretation System",
    "Transportation",
    "Wheelchair Accessible",
    "Wi-Fi Access",
    "Youth Room / Teen Center"
  ],
  languages: [
    "English",
    "Spanish",
    "French",
    "Portuguese",
    "German",
    "Italian",
    "Yoruba",
    "Igbo",
    "Twi",
    "Swahili",
    "Arabic",
    "Mandarin",
    "Cantonese",
    "Korean",
    "Tagalog",
    "Hindi",
    "Urdu",
    "Tamil",
    "Telugu",
    "Polish",
    "Romanian",
    "Russian",
    "Ukrainian"
  ],
  ministryExperience: [
    "Children's Ministry",
    "Evangelism / Outreach",
    "Missions / Global Outreach",
    "Pastoral Care",
    "Worship Ministry",
    "Youth Ministry"
  ],
  skills: [
    "Bible Study Facilitation",
    "Biblical Counseling",
    "Church Leadership",
    "Conflict Resolution",
    "Deliverance / Healing Ministry",
    "Discipleship",
    "Entrepreneurship / Business Leadership",
    "Evangelism / Outreach",
    "Event Planning / Coordination",
    "Financial Stewardship",
    "Pastoral Care",
    "Prayer Leadership",
    "Preaching / Teaching",
    "Servant Leadership",
    "Spiritual Mentorship",
    "Strategic Planning",
    "Team Building",
    "Time Management",
    "Vision Casting",
    "Volunteer Management",
    "Worship Leadership",
    "Youth / Family Empowerment"
  ],
  rolesInterested: [
    "Associate Pastor / Assistant Pastor",
    "Campus / Student Pastor",
    "Chaplain / Hospital Ministry",
    "Children’s Ministry Volunteer",
    "Children’s Pastor / Kids Ministry Leader",
    "Choir / Vocalist",
    "Church Administrator / Office Staff",
    "Communications / Social Media Coordinator",
    "Community Service Volunteer",
    "Counseling / Pastoral Care",
    "Creative Arts / Drama / Dance",
    "Event Planner / Coordinator",
    "Facilities / Maintenance Manager",
    "Finance / Treasurer",
    "Graphic Design / Marketing",
    "IT / Technical Support",
    "Lead Pastor / Senior Pastor",
    "Media / Audio-Visual Team",
    "Mentoring / Coaching",
    "Ministry Team Leader",
    "Missions / Outreach Volunteer",
    "Outreach / Evangelism Pastor",
    "Photography / Videography",
    "Prayer Ministry Team",
    "Reception / Welcome Team",
    "Small Group / Discipleship Leader",
    "Sunday School Teacher",
    "Teaching / Bible Study Leader",
    "Volunteer Coordinator",
    "Worship Pastor / Music Director",
    "Worship Team / Musician",
    "Youth Group Leader",
    "Youth Pastor / Youth Leader"
  ],
  training: [
    "Ordination Training",
    "Chaplaincy Training",
    "Counseling / Pastoral Care Training",
    "Leadership Development Training",
    "Missionary Training"
  ]
};

